//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalSearchEngine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Images = new HashSet<Image>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ItemType { get; set; }
        public string FolderPath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Size { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
